version: '3.8'

services:
  blockapp:
    image: 192.168.0.101:5000/blockapp:latest
    container_name: blockapp
    ports:
      - "71:80"
      - "5001:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT:-5000}
    restart: always
    command: sh -c "nginx -g 'daemon off;' & node server.js"
